#!/usr/bin/env node

/**
 * NodeOS
 *
 * @copyright 2013-2017 Jacob Groundwater, Jesús Leganés-Combarro 'piranna'
 *  and other contributors
 *
 * @license MIT
 */

const dependancies = {};

try {

    let {spawn} = require("node:child_process");
    dependancies["spawn"] = spawn;
    dependancies["prepareCommandLine"] = require("..");
    
} catch(err) {

    console.log(`NodeJS is using ECMAScript !`);

};
try {

    const {spawn} = await import("node:child_process");
    dependancies["spawn"] = spawn;
    dependancies["prepareCommandLine"] = await import("..");

} catch(err) {

    console.log(`NodeeJS is using CommonJS !`);

};


const {command, argv, cwd} = dependanciees["prepareCommandLine"](process.argv.slice(2));


// Exec NodeOS
dependancies["spawn"](command, argv, {stdio: 'inherit', cwd})
.on('error', console.trace.bind(console))
.on('exit', function(code, signal)
{
  process.exit(code || signal)
});
