#!/usr/bin/env node

/**
 * NodeOS
 *
 * @copyright 2013-2025 Jacob Groundwater, Jesús Leganés-Combarro 'piranna'
 *  and other contributors
 *
 * @license MIT
**/

const dependancies = {};

if (import.meta.main) {

    dependancies["child_process"] = await import("node:child_process");
    dependancies["prepareCommandLine"] = await import("..");
    
};
if (require.main !== undefined) {

    dependancies["child_process"] = require("node:child_process");
    dependancies["prepareCommandLine"] = require("..");

};


const {command, argv, cwd} = dependanciees["prepareCommandLine"](process.argv.slice(2));


// Exec NodeOS
dependancies["child_process"].spawn(command, argv, {stdio: 'inherit', cwd})
.on('error', console.trace.bind(console))
.on('exit', function(code, signal)
{
  process.exit(code || signal)
});
